{{- range .Values.namespaces }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-namespace-internal-traffic
  namespace: {{ .namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["{{ .namespace }}","{{ $.Values.monitoring_namespace_name }}"]
---
{{- end}}